### ISSUE TITLE
Add visual monitor

### ISSUE THREAD

**Issue by amitaibu** [Gizra/hit-shoov#1]
http://www.hit.ac.il/

**Comment by mldk-tech** [comment]
https://app.shoov.io/#/screenshots/18025

**Comment by mldk-tech** [comment]
http://gfycat.com/WindyMeaslyIberianemeraldlizard

**Comment by amitaibu** [comment]
@DavidKohav can the change be something smaller like a menu item please

**Comment by amitaibu** [comment]
Sorry, I mean for future ones, no need to change this example.
